sll-185: Add self-signed CERT as trusted and import GPG keys

diff --git a/public/tools/rmt-client-setup-res b/public/tools/rmt-client-setup-res
--- a/public/tools/rmt-client-setup-res
+++ b/public/tools/rmt-client-setup-res
@@ -10,6 +10,8 @@ SUSECONNECT=/usr/bin/SUSEConnect
 RPM=/usr/bin/rpm
 DNF=/usr/bin/dnf
 CURL=/usr/bin/curl
+TEMPFILE="/etc/pki/ca-trust/source/anchors/rmt.crt"
+UPDATE_CA_TRUST=/usr/bin/update-ca-trust
 
 PARAMS=$@
 
@@ -79,6 +81,30 @@ if [ ! -x $CURL ]; then
     exit 1
 fi
 
+# Import Self-signed CERT as Trusted
+if [ -z "$REGCERT" ]; then
+    CERTURL=`echo "$REGURL" | awk -F/ '{print "https://" $3 "/rmt.crt"}'`
+else
+    CERTURL="$REGCERT"
+fi
+
+if [ -x $CURL ]; then
+    $CURL --tlsv1.2 --silent --insecure --connect-timeout 10 --output $TEMPFILE $CERTURL
+    if [ $? -ne 0 ]; then
+        echo "Download failed. Abort."
+        exit 1
+    fi
+else
+    download_tool_basename=$(basename $CURL)
+    echo "Binary to download the certificate not found. Please install $download_tool_basename. Abort."
+    exit 1
+fi
+
+if [ -x $UPDATE_CA_TRUST ]; then
+    $UPDATE_CA_TRUST enable
+    $UPDATE_CA_TRUST extract
+fi
+
 SLL_version=`cat /etc/os-release | grep "VERSION_ID" | cut -d\" -f2 | cut -d\. -f1`
 if [[ ${SLL_version} > 8 ]]; then                                                                                                       
    SLL_name="SLL";                                                                                                                
@@ -105,6 +131,10 @@ if [ -f /etc/dnf/protected.d/redhat-release.conf ]; then
     rm -f /etc/dnf/protected.d/redhat-release.conf;
 fi
 
+echo "Importing repomd.xml.key"
+$CURL --silent --show-error --insecure  ${REGURL}/repo/SUSE/Updates/${SLL_name}/${SLL_version}/x86_64/update/repodata/repomd.xml.key --output repomd.xml.key
+$RPM --import repomd.xml.key
+
 if [ ! -x $SUSECONNECT ]; then
     echo "Downloading SUSEConnect"
 
@@ -124,9 +154,6 @@ fi
 $CURL --silent --show-error --insecure $REGURL/tools/rmt-client-setup --output rmt-client-setup
 echo "Running rmt-client-setup $PARAMS"
 sh rmt-client-setup $PARAMS
-
-echo "Importing repomd.xml.key"
-$RPM --import ${REGURL}/repo/SUSE/Updates/${SLL_name}/${SLL_version}/x86_64/update/repodata/repomd.xml.key
 
 if [[ ${SLL_version} > 8 ]]; then 
     systemctl start suseconnect-keepalive.timer
