Indent consistently

diff --git a/public/tools/rmt-client-setup b/public/tools/rmt-client-setup
--- a/public/tools/rmt-client-setup
+++ b/public/tools/rmt-client-setup
@@ -42,28 +42,28 @@ exit 1
 
 function http_get_signing_keys_index_html()
 {
-  local index_html_url=`echo "$REGURL" | awk -F/ '{print "https://" $3 "/repo/keys/"}'`
+    local index_html_url=`echo "$REGURL" | awk -F/ '{print "https://" $3 "/repo/keys/"}'`
 
-  $CURL --insecure --fail --output $TMPDIR/index.html $index_html_url
+    $CURL --insecure --fail --output $TMPDIR/index.html $index_html_url
 
-  return $?
+    return $?
 }
 
 function parse_index_html()
 {
-  KEY_FILES=()
-  while read line; do
-    # This is no substitute for a HTML parser, and probably only works on the index.html generated by RMT
-    KEY_FILES+=(`echo $line | sed -n "/href/ s/.*href=['\"]\([^'\"]*\)['\"].*/\1/gp"`)
-  done < $TMPDIR/index.html
+    KEY_FILES=()
+    while read line; do
+        # This is no substitute for a HTML parser, and probably only works on the index.html generated by RMT
+        KEY_FILES+=(`echo $line | sed -n "/href/ s/.*href=['\"]\([^'\"]*\)['\"].*/\1/gp"`)
+    done < $TMPDIR/index.html
 }
 
 function http_get_key_file()
 {
-  local key_file_url=`echo "$REGURL/$1" | awk -F/ '{print "https://" $3 "/repo/keys/" $4}'`
-  echo "Getting '$1' from $key_file_url"
-  $CURL --silent --fail --output "$TMPDIR/$1" $key_file_url
-  return $?
+    local key_file_url=`echo "$REGURL/$1" | awk -F/ '{print "https://" $3 "/repo/keys/" $4}'`
+    echo "Getting '$1' from $key_file_url"
+    $CURL --silent --fail --output "$TMPDIR/$1" $key_file_url
+    return $?
 }
 
 function import_key
@@ -104,34 +104,34 @@ function import_key
 
 function import_signing_keys()
 {
-  TMPDIR=`mktemp -d /tmp/rmtsetup-XXXXXXXX`;
+    TMPDIR=`mktemp -d /tmp/rmtsetup-XXXXXXXX`;
 
-  if [ -z $TMPDIR ]; then
-    echo "Cannot create tmpdir for key import in /tmp. Abort."
-    exit 1
-  fi
+    if [ -z $TMPDIR ]; then
+        echo "Cannot create tmpdir for key import in /tmp. Abort."
+        exit 1
+    fi
 
-  http_get_signing_keys_index_html
-  local retval=$?
+    http_get_signing_keys_index_html
+    local retval=$?
 
-  if [ $retval -eq 22 ]; then
-    echo "Custom keys directory 'repo/keys' on RMT server is not accessible. Check it exists and is readable and searchable by RMT process."
-  else
-    parse_index_html
-    for i in "${KEY_FILES[@]}"; do
-      if [[ $i == *.key ]]; then
-        http_get_key_file $i
-        if [ $? -eq 22 ]; then
-          echo "Custom key '$i' on RMT server is not accessible. Check permissions."
-          continue
-        else
-          import_key $i
-        fi
-      fi
-    done
-  fi
+    if [ $retval -eq 22 ]; then
+        echo "Custom keys directory 'repo/keys' on RMT server is not accessible. Check it exists and is readable and searchable by RMT process."
+    else
+        parse_index_html
+        for i in "${KEY_FILES[@]}"; do
+            if [[ $i == *.key ]]; then
+                http_get_key_file $i
+                if [ $? -eq 22 ]; then
+                    echo "Custom key '$i' on RMT server is not accessible. Check permissions."
+                    continue
+                else
+                    import_key $i
+                fi
+            fi
+        done
+    fi
 
-  rm -rf $TMPDIR/
+    rm -rf $TMPDIR/
 }
 
 AUTOACCEPT=""
